### ISSUE TITLE
Nix build failing (exit 1) without erroring?

### ISSUE THREAD

**Issue by diamondburned** [DBCDK/morph#76]
I was trying to deploy this over GitLab's CI using `morph`, but `morph` keeps failing. Here's the CI output: https://0x0.st/zylt.txt

From the output, I can't seem to point out any errors, it just seems like `nix-build` just exited 1 for whatever reason. How do I debug?

CI:

```yml
image: nixos/nix

variables:
  SSH_SKIP_HOST_KEY_CHECK: "1"

morph:
  cache:
    key: nix
    paths:
      - .nix/
  before_script:
    # Different /nix/store path
    - mkdir -p "$PWD/.nix"
    - mv -f /nix/* "$PWD/.nix/"
    - mount -o bind "$PWD/.nix" /nix
    # Add the stable channel and update
    - nix-channel --add https://nixos.org/channels/nixos-unstable nixos
    - nix-channel --update
    # Install dependencies
    - nix-env -iA nixos.git nixos.gnutar
    - nix-env -iA nixos.morph nixos.openssh
    # Change the permission of the private key so SSH can be happy
    - chown root "$SSH_IDENTITY_FILE"
    - chmod 600 "$SSH_IDENTITY_FILE"
  script:
    - export GIT_SSH_COMMAND="ssh -i $SSH_IDENTITY_FILE -o StrictHostKeyChecking=no"
    #- morph build default.nix
    #- morph deploy default.nix test
    - morph deploy default.nix switch

```

`morph` version: 1.3.0 from NixOS Unstable
